on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'extras/**'
      - .dockerignore
      - .gitignore
      - Dockerfile
      - LICENSE
      - README.md

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH
      - run: python3 shared/script/deploy.py
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: skija-shared
          path: shared/target/*.jar

  macos:
    runs-on: macos-10.15
    needs: shared
    strategy:
      matrix:
        arch: ["x64", "arm64"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH
      - run: python3 native/script/build.py --arch=${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: skija-macos-${{ matrix.arch }}
          path: native/build/*.dylib
      - uses: actions/download-artifact@v4.1.7
        with:
          name: skija-shared
      - name: Test
        if: ${{ matrix.arch == 'x64'}}
        run: python3 shared/script/test.py --skija-shared skija-shared-$(python3 script/revision.py).jar
      - run: python3 native/script/deploy.py --arch=${{ matrix.arch }}
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}

  linux:
    runs-on: ubuntu-16.04
    needs: shared
    steps:
      - run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH
          sudo apt-get --quiet --yes install ninja-build libglu1-mesa-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
          sudo update-alternatives --config gcc
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: python3 native/script/build.py
      - uses: actions/upload-artifact@v2
        with:
          name: skija-linux
          path: native/build/*.so
      - uses: actions/download-artifact@v4.1.7
        with:
          name: skija-shared
      - run: python3 shared/script/test.py --skija-shared skija-shared-$(python3 script/revision.py).jar
      - run: python3 native/script/deploy.py
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}

  windows:
    runs-on: windows-2019
    needs: shared
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - shell: bash
        run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH
      - run: python3 native/script/build.py
      - uses: actions/upload-artifact@v2
        with:
          name: skija-windows
          path: |
            native/build/*.dll
            native/build/icudtl.dat
      - uses: actions/download-artifact@v4.1.7
        with:
          name: skija-shared
      - shell: bash
        run: python3 shared/script/test.py --skija-shared skija-shared-$(python3 script/revision.py).jar
      - run: python3 native/script/deploy.py
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
